version: '3'

services:

  # ----------------------------------------
  # OpsCenter
  # ----------------------------------------
  opscenter:
    image: "datastax/dse-opscenter:6.8.0"
    ports:
      - 8888:8888
    environment:
      - DS_LICENSE=accept

  studio:
    image: datastax/dse-studio:6.8.1
    environment:
      - DS_LICENSE=accept
    ports:
      - "9091:9091"
    depends_on:
      - seed_node
    container_name: "studio"

  seed_node:
    image: datastax/dse-server:6.8.1
    command: [ -s -k ]
    environment:
      - DS_LICENSE=accept
      - DC=DC1
      - JVM_EXTRA_OPTS=-Xms1g -Xmx2g
      - NUM_TOKENS=8
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1

  node:
    image: datastax/dse-server:6.8.1
    command: [ -s -k ]
  #  ports:
  #  - "9042:9042"
  #  - "8983:8983"
  #  - "8182:8182"
    environment:
      - DS_LICENSE=accept
      - SEEDS=seed_node
      - DC=DC1
      - JVM_EXTRA_OPTS=-Xms1g -Xmx2g
      - NUM_TOKENS=8
    links:
      - seed_node
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
